import { Antic_Didone, Albert_Sans } from 'next/font/google';
import './globals.css';
import Navbar from './navbar/page';
import Footer from './footer/page';
import ShopContextProvider from './Context/ShopContext';



export const anticDidone = Antic_Didone({
  subsets: ['latin'],
  weight:'400',
  variable: '--font-anticdidone',
})

  export const albertSans = Albert_Sans({
    subsets: ['latin'],
    weight:'400',
    variable: '--font-albertsans',
  })

export const metadata = {
  title: 'Glow Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ShopContextProvider>
     <html lang="en" className={`${albertSans.variable} font-sans ${anticDidone.variable} font-serif`}>
       <body>
          <Navbar />
            {children}
          <Footer />
        </body>
     </html>
    </ShopContextProvider>

  )
}
